openapi: 3.0.0
info:
  title: kytos/status
  version: latest
  description: Provides basic information about the controller status
paths:
  /api/kytos/status/v1/:
    get:
      summary: Return basic information from running controller.
      responses:
        200:  # You can add more responses
          description: Describe a successful call.
          content:
            application/json:  # You can also use text/plain, for example
              schema:
                type: object  # Adapt to your response
                properties:
                  prop_one:
                    type: string
                    description: Meaning of prop_one
                    example: an example of prop_one
                  second_prop:
                    type: integer
                    description: Meaning of second_prop
                    example: 42
  /api/kytos/status/v1/napps:
    get:
      summary: Return a list of all NApps installed and running.
      responses:
        200:  # You can add more responses
          description: Describe a successful call.
          content:
            application/json:  # You can also use text/plain, for example
              schema:
                type: object  # Adapt to your response
                properties:
                  prop_one:
                    type: string
                    description: Meaning of prop_one
                    example: an example of prop_one
                  second_prop:
                    type: integer
                    description: Meaning of second_prop
                    example: 42
